# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Julian-Samuel Gebühr
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform listmonk installation tasks
  block:
    - name: Validate listmonk configuration
      when: listmonk_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install listmonk
      when: listmonk_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-listmonk
    - install-all
    - install-listmonk

- name: Perform listmonk uninstallation tasks
  block:
    - name: Uninstall listmonk
      when: not listmonk_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-listmonk
