# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Julian-Samuel Gebühr
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "listmonk_database_host", "new": "listmonk_database_hostname" }
    - { "old": "listmonk_environment_variables_extension", "new": "listmonk_environment_variables_additional_variables" }

- name: Fail if required listmonk settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - listmonk_identifier
    - listmonk_uid
    - listmonk_gid
    - listmonk_hostname
    - listmonk_path_prefix
    - listmonk_container_network

- name: Run if Traefik is enabled
  when: listmonk_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Appsmith are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - listmonk_container_labels_traefik_hostname
        - listmonk_container_labels_traefik_path_prefix

    - name: Fail if listmonk_container_labels_traefik_path_prefix is different than /
      ansible.builtin.fail:
        msg: >-
          listmonk_container_labels_traefik_path_prefix (`{{ listmonk_container_labels_traefik_path_prefix }}`) must be `/`.
          listmonk does not support hosting under a subpath yet.
      when: "listmonk_container_labels_traefik_path_prefix != '/'"

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `listmonk_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if listmonk_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          listmonk_container_labels_traefik_path_prefix (`{{ listmonk_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/listmonk`).
      when: "listmonk_container_labels_traefik_path_prefix != '/' and listmonk_container_labels_traefik_path_prefix[-1] == '/'"
